export interface NetworkField {
  id: string
  name: string
  nameForDisplay: string
  chainId: number
  rpcUrl: string
  explorerUrl: string
  iconUrl: string
  symbol: string
  failoverRpcUrl?: string
  blockTime?: number
}

export interface NetworkRegistry {
  category: string
  networks: NetworkField[]
}

export const NETWORKS_REGISTRY: NetworkRegistry[] = [
  {
    category: 'popular',
    networks: [
      {
        id: 'ethereum-mainnet',
        name: 'eth-mainnet',
        nameForDisplay: 'Ethereum Mainnet',
        chainId: 1,
        rpcUrl: 'https://ethereum-rpc.publicnode.com',
        explorerUrl: 'https://etherscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://eth.llamarpc.com',
        blockTime: 12,
      },
      {
        id: 'bnb-smart-chain',
        name: 'bnb-mainnet',
        nameForDisplay: 'BNB Smart Chain',
        chainId: 56,
        rpcUrl: 'https://bsc-dataseed.bnbchain.org',
        explorerUrl: 'https://bscscan.com',
        iconUrl: 'https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png',
        symbol: 'BNB',
        failoverRpcUrl: 'https://bsc.llamarpc.com',
        blockTime: 3,
      },
      {
        id: 'polygon-mainnet',
        name: 'polygon-mainnet',
        nameForDisplay: 'Polygon Mainnet',
        chainId: 137,
        rpcUrl: 'https://polygon.publicnode.com',
        explorerUrl: 'https://polygonscan.com',
        iconUrl: 'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
        symbol: 'POL',
        failoverRpcUrl: 'https://polygon.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'arbitrum-mainnet',
        name: 'arb-mainnet',
        nameForDisplay: 'Arbitrum Mainnet',
        chainId: 42161,
        rpcUrl: 'https://public-arb-mainnet.fastnode.io',
        explorerUrl: 'https://arbiscan.io',
        iconUrl:
          'https://assets.coingecko.com/coins/images/16547/large/photo_2023-03-29_21.47.00.jpeg',
        symbol: 'ARB',
        failoverRpcUrl: 'https://arb.llamarpc.com',
        blockTime: 1,
      },
      {
        id: 'optimism-mainnet',
        name: 'op-mainnet',
        nameForDisplay: 'Optimism Mainnet',
        chainId: 10,
        rpcUrl: 'https://mainnet.optimism.io',
        explorerUrl: 'https://optimistic.etherscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/25244/large/Optimism.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://optimism.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'base-mainnet',
        name: 'base-mainnet',
        nameForDisplay: 'Base Mainnet',
        chainId: 8453,
        rpcUrl: 'https://mainnet.base.org',
        explorerUrl: 'https://basescan.org',
        iconUrl: 'https://assets.coingecko.com/coins/images/32480/large/base.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://base.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'avalanche-mainnet',
        name: 'avax-mainnet',
        nameForDisplay: 'Avalanche C-Chain',
        chainId: 43114,
        rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
        explorerUrl: 'https://snowtrace.io',
        iconUrl:
          'https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png',
        symbol: 'AVAX',
        failoverRpcUrl: 'https://avalanche.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'hyperevm-mainnet',
        name: 'hyperevm-mainnet',
        nameForDisplay: 'HyperEVM',
        chainId: 999,
        rpcUrl: 'https://hyperliquid-mainnet.g.alchemy.com/v2/YOUR_KEY',
        explorerUrl: 'https://purrsec.com',
        iconUrl: 'https://assets.coingecko.com/coins/images/52510/large/hyperliquid.png',
        symbol: 'HYPE',
        failoverRpcUrl: 'https://rpc.hyperliquid.xyz/evm',
        blockTime: 1,
      },
      {
        id: 'unichain-mainnet',
        name: 'unichain-mainnet',
        nameForDisplay: 'Unichain Mainnet',
        chainId: 130,
        rpcUrl: 'https://mainnet.unichain.org',
        explorerUrl: 'https://uniscan.xyz',
        iconUrl: 'https://assets.coingecko.com/coins/images/25244/large/Optimism.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://unichain.llamarpc.com',
        blockTime: 1,
      },
      {
        id: 'gnosis-mainnet',
        name: 'gnosis-mainnet',
        nameForDisplay: 'Gnosis Chain',
        chainId: 100,
        rpcUrl: 'https://rpc.gnosischain.com',
        explorerUrl: 'https://gnosisscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/662/large/logo_square_simple_300px.png',
        symbol: 'xDAI',
        failoverRpcUrl: 'https://gnosis.llamarpc.com',
        blockTime: 5,
      },
      {
        id: 'mantle-mainnet',
        name: 'mantle-mainnet',
        nameForDisplay: 'Mantle Mainnet',
        chainId: 5000,
        rpcUrl: 'https://rpc.mantle.xyz',
        explorerUrl: 'https://mantlescan.xyz',
        iconUrl: 'https://assets.coingecko.com/coins/images/30980/large/token-logo.png',
        symbol: 'MNT',
        failoverRpcUrl: 'https://mantle.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'celo-mainnet',
        name: 'celo-mainnet',
        nameForDisplay: 'Celo Mainnet',
        chainId: 42220,
        rpcUrl: 'https://forno.celo.org',
        explorerUrl: 'https://celoscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/11090/large/InjXBNx9_400x400.jpg',
        symbol: 'CELO',
        failoverRpcUrl: 'https://celo.llamarpc.com',
        blockTime: 5,
      },
      {
        id: 'blast-mainnet',
        name: 'blast-mainnet',
        nameForDisplay: 'Blast Mainnet',
        chainId: 81457,
        rpcUrl: 'https://rpc.blast.io',
        explorerUrl: 'https://blastscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/35494/large/Blast.jpg',
        symbol: 'ETH',
        failoverRpcUrl: 'https://blast.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'berachain-mainnet',
        name: 'berachain-mainnet',
        nameForDisplay: 'Berachain Mainnet',
        chainId: 80094,
        rpcUrl: 'https://rpc.berachain.com',
        explorerUrl: 'https://berascan.com',
        iconUrl: 'https://assets.coingecko.com/coins/images/36417/large/bera.png',
        symbol: 'BERA',
        failoverRpcUrl: 'https://berachain.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'linea-mainnet',
        name: 'linea-mainnet',
        nameForDisplay: 'Linea Mainnet',
        chainId: 59144,
        rpcUrl: 'https://rpc.linea.build',
        explorerUrl: 'https://lineascan.build',
        iconUrl: 'https://assets.coingecko.com/coins/images/32234/large/linea.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://linea.llamarpc.com',
        blockTime: 2,
      },
      {
        id: 'scroll-mainnet',
        name: 'scroll-mainnet',
        nameForDisplay: 'Scroll Mainnet',
        chainId: 534352,
        rpcUrl: 'https://rpc.scroll.io',
        explorerUrl: 'https://scrollscan.com',
        iconUrl: 'https://assets.coingecko.com/coins/images/32760/large/scroll.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://scroll.llamarpc.com',
        blockTime: 3,
      },
      {
        id: 'plasma-mainnet',
        name: 'plasma-mainnet',
        nameForDisplay: 'Plasma Mainnet',
        chainId: 9745,
        rpcUrl: 'https://rpc.plasma.to',
        explorerUrl: 'https://plasmascan.to',
        iconUrl: '',
        symbol: 'XPL',
        blockTime: 1,
      },
    ],
  },
  {
    category: 'custom',
    networks: [
      {
        id: 'sepolia-eth',
        name: 'eth-sepolia',
        nameForDisplay: 'ETH Sepolia Testnet',
        chainId: 11155111,
        rpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com',
        explorerUrl: 'https://sepolia.etherscan.io',
        iconUrl: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
        symbol: 'ETH',
        failoverRpcUrl: 'https://eth-sepolia.llamarpc.com',
        blockTime: 12,
      },
    ],
  },
]
